default_context:
  _pegasus_version: 2024.8.2
  ai_chat_mode: openai
  ai_image_mode: none
  author_name: Chris
  ci: github_actions
  css_framework: tailwind
  css_theme: default
  database: postgres
  deploy_platform: digital_ocean_app_platform
  description: This is an LCP application for Kincaid Wolstein Vocational and Rehabilitation
    Services
  docker_setup: default
  domain_name: localhost:8000
  email: christophertskerritt@gmail.com
  enable_github_login: n
  enable_google_login: y
  enable_twitter_login: n
  front_end_framework: htmx
  include_static_files: y
  marketing_email_platform: none
  post_process: y
  project_name: Kincaid Wolstein LifeCarePlan Application
  project_slug: lifecareplan
  standalone_front_end: none
  stripe_payment_mode: checkout
  subscription_billing_model: default
  subscription_pricing_ui: in_app
  use_2fa: y
  use_admin_docs: n
  use_api_auth: n
  use_api_keys: y
  use_async_example: n
  use_cloud_media_storage: y
  use_debug_toolbar: y
  use_docker: y
  use_ecommerce_example: n
  use_examples: y
  use_health_checks: y
  use_impersonation: y
  use_sentry: y
  use_subscriptions: n
  use_teams: y
  use_teams_example: y
  use_translations: y
  use_wagtail: n
