
databases:
- engine: PG
  name: lifecareplan-db
  num_nodes: 1
  size: db-s-dev-database
  version: "14"
- cluster_name: lifecareplan-redis
  engine: REDIS
  name: lifecareplan-redis
  production: true
  version: "7"
name: lifecareplan
region: nyc
services:
- dockerfile_path: Dockerfile.web
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${lifecareplan-db.DATABASE_URL}
  - key: DJANGO_SETTINGS_MODULE
    scope: RUN_AND_BUILD_TIME
    value: lifecareplan.settings_production
  - key: SECRET_KEY
    scope: RUN_AND_BUILD_TIME
    value: 'django-insecure-7hQGrgmxmxehmk06qJ0c0mkFeMWzz1FA3nPeTOHum9C6ePucihvT1gGXf0W9'
  - key: REDIS_URL
    scope: RUN_TIME
    value: ${lifecareplan-redis.DATABASE_URL}
  github:
    branch: main
    deploy_on_push: true
    repo: YOUR_GITHUB_USERNAME/lifecareplan
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: lifecareplan-web
  routes:
  - path: /
workers:
- dockerfile_path: Dockerfile.web
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${lifecareplan-db.DATABASE_URL}
  - key: DJANGO_SETTINGS_MODULE
    scope: RUN_AND_BUILD_TIME
    value: lifecareplan.settings_production
  - key: SECRET_KEY
    scope: RUN_AND_BUILD_TIME
    value: 'django-insecure-7hQGrgmxmxehmk06qJ0c0mkFeMWzz1FA3nPeTOHum9C6ePucihvT1gGXf0W9'
  - key: REDIS_URL
    scope: RUN_TIME
    value: ${lifecareplan-redis.DATABASE_URL}
  github:
    branch: main
    deploy_on_push: true
    repo: YOUR_GITHUB_USERNAME/lifecareplan
  instance_count: 1
  instance_size_slug: basic-xs
  name: lifecareplan-celery
  run_command: celery -A lifecareplan worker -l INFO --pool=gevent --concurrency 2
